Implement attach + tests, re-atttach + tests
szwos/Nokia-PK-2023 pull request #2
Opened 2023-04-24 02:45 UTC by mik155

2023-04-24 10:40 UTC, rvbnsk commented
General comment before review. Please turn on lint from github workflows. It should be present in PR

2023-04-24 11:22 UTC, rvbnsk requested changes
Generally OK, please fix minor things

2023-04-24 11:22 UTC, rvbnsk commented on src/UE/Tests/Application/ApplicationTestSuite.cpp
> -}
Probably you should fix indentation. "class" should not be indented and it was OK before

2023-04-24 11:22 UTC, rvbnsk commented on src/UE/Tests/Application/ApplicationTestSuite.cpp
> +        const common::BtsId btsId{333};
keep c++11 brace init formatting style:
```c++
const common::PhoneNumber PHONE_NUMBER{ 112 };
const common::BtsId btsId{ 333 };
```

2023-04-24 11:22 UTC, rvbnsk commented on src/UE/Tests/Application/ApplicationTestSuite.cpp
> +        EXPECT_CALL(timerPortMock, startTimer(Duration(500)));
magic number, exctract into variable

2023-04-24 11:22 UTC, rvbnsk commented on src/UE/Tests/Application/ApplicationTestSuite.cpp
> +                                    timerPortMock};
as comment above

2023-04-24 11:22 UTC, rvbnsk commented on src/UE/Tests/Application/ApplicationTestSuite.cpp
> +           objectUnderTest.handleAttachReject();
extra indentation, fix please

2023-04-24 11:22 UTC, rvbnsk commented on src/UE/Tests/Application/ApplicationTestSuite.cpp
> +           objectUnderTest.handleBTSDisconnected();
extra indentation

2023-04-24 11:22 UTC, rvbnsk commented on src/UE/Tests/Application/ApplicationTestSuite.cpp
> +           objectUnderTest.handleBTSDisconnected();
extra indentation

2023-04-24 11:22 UTC, rvbnsk commented on src/UE/Tests/Application/ApplicationTestSuite.cpp
> +
blank lines, remove

2023-04-24 11:22 UTC, rvbnsk commented on src/UE/Tests/Application/ApplicationTestSuite.cpp
> +
only one extra blank line should be present before namespace ending

2023-04-24 11:22 UTC, rvbnsk commented on src/UE/Tests/Application/ApplicationTestSuite.cpp
>  }
```c++
} // namespace ue
```
For better readability keep informing when namespace ends

2023-04-24 11:22 UTC, rvbnsk commented on src/UE/Tests/Application/Ports/BtsPortTestSuite.cpp
> +
extra blank line, remove

2023-04-24 11:22 UTC, rvbnsk commented on src/UE/Tests/Application/Ports/BtsPortTestSuite.cpp
> +
is this a kind of letfover? It should be left like this?

2023-05-08 09:41 UTC, rvbnsk requested changes
Sory for waiting for a review for a long time 😉

2023-05-08 09:41 UTC, rvbnsk commented on src/UE/Tests/Application/ApplicationTestSuite.cpp
> +//RE-ATTACH
comment as in standard, eg:
```cpp
// RE-ATTACH
```
Let's keep the code clean 😉

2023-05-08 09:41 UTC, rvbnsk commented on src/UE/Tests/Application/ApplicationTestSuite.cpp
> +//********************************************************************************************
remove

2023-05-08 09:41 UTC, rvbnsk commented on src/UE/Application/Ports/TimerPort.cpp
>  }
comment end of namespace

2023-05-08 09:41 UTC, rvbnsk commented on src/UE/Application/Ports/TimerPort.hpp
> +#include <thread>
what is this includes for?
For std::mutex you could use
```cpp
#include <mutex>
```
for condition_variable use:
```cpp
#include <condition_variable>
```
I think future is not needed here

2023-05-12 23:07 UTC, mik155 commented on src/UE/Application/Ports/TimerPort.cpp
> +        handler->handleTimeout();
- Could cond_lock be const? - compiler doesn't like that

2023-05-14 17:00 UTC, rvbnsk requested changes

2023-05-14 17:00 UTC, rvbnsk commented on src/UE/Tests/Application/ApplicationTestSuite.cpp
> +    const long bts_response_time_ms = 500;
constexpr

2023-05-14 17:00 UTC, rvbnsk commented on src/UE/Tests/Application/ApplicationTestSuite.cpp
> +
remove blank line

2023-05-22 18:11 UTC, rvbnsk approved these changes
lgtm

2023-05-22 18:11 UTC, rvbnsk approved these changes

2023-05-22 21:33 UTC, szwos approved these changes

2023-05-29 16:34 UTC, merged